server:
  port: 9000
  servlet:
    context-path: /xigua
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
zuul:
  ignored-services: '*'
  prefix: /maomi
  routes:
    employee:                           #自定义路由规则的名称，在底层数据结构中是map的键
      serviceId: atguigu-feign-consumer
      path: /zuul-emp/**

