server:
  port: 1000
eureka:
  client:
    service-url:              #配置当前微服务作为Eureka客户端访问Eureka服务器端时使用的地址
      defaultZone:  http://localhost:5000/eureka/
spring:
  application:
    name: atguigu-provider    #指定当前微服务名称，以便将来通过微服务名称调用当前微服务能够找到
management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream